## Numpy
+ 可做到的功能
  + 快速的多維陣列操作。
  + 可靠的科學功能函數庫。
  + 可協助繪圖工具進行繪圖。
+ NumPy 是幾乎每個科學 Python 應用程序或模組的核心，它提供了以向量化形式的快速 N-d 陣列類型可供操作。

In [4]:
import numpy as np
a = [1,2,3,5,7,9]
b = [3,5,3,6,7,9]
print(type(a))
print(a + b)
np1 = np.array(a)
np2 = np.array(b)
print(type(np1))
print(type(np2))
print(np1 + np2)

<class 'list'>
[1, 2, 3, 5, 7, 9, 3, 5, 3, 6, 7, 9]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[ 4  7  6 11 14 18]


+ ndarray.ndim
   + 維度的數量。
+ ndarray.shape
   + 顯示出陣列在每個維度上的整數值。
+ ndarray.size
   + 陣列內元素的總數。
+ ndarray.dtype
   + 用來描述陣列中元素類型的對象。

In [13]:
import numpy as np
i = np.array([1,2,3]) #所有內容類型必須一樣
#有字串所有都轉成字串
#有浮點數所有都轉成浮點數
print(i.ndim)
print(i.shape)
print(i.size)
print(i.dtype)

1
(3,)
3
int32


https://www.runoob.com/numpy/numpy-dtype.html

In [19]:
import numpy as np
v1 = np.array([1,2,3],dtype=np.int8)
print(v1.dtype)
v2 = np.array([1,2.5,3],dtype=np.float16)
print(v2.dtype)
v3 = np.array([1,2.5,"Test"])
print(v3.dtype)

int8
float16
<U32


In [25]:
import numpy as np
i = [[5,6,7],
     [8,9,15]]#2x3
a = np.array(i)
print(a.ndim)
# 軸0有2筆數值
# 軸1有3筆數值
print(a.shape)
print(a.shape[0])
print(a.shape[1])
print(a.size)

2
(2, 3)
2
3
6


## 陣列初始化與重新規劃
+ 針對初始化這部分提供了多種方式：
+ 不做初始化
   + 例如：np.empty((2,4))
+ 全部規劃為 0
   + 例如：np.zeros((3,4))
+　全部規劃為 1
  + np.ones((5,2))
+ 全部規劃／填滿為某數，例如 6
   + 例如： np.full((3,3),6)
+ 建立對角矩陣，對角皆為 1，其他為 0
   + 例如： np.eye(3)
+ 建立對角矩陣，對角為 1,2,3,4，其他為 0
   + 例如： np.diag([1,2,3,4])
+ reshape((x,y)) 這個指令就可以將現有的陣列  重新規劃為 x 乘以 y 的陣列。 
+ np.arange(起始值, 結束值, 固定間隔)：也是產生一維陣列，和 np.array( ) 的差別在於 arange 擁有較大的彈性，而且元素數值是自動化產生。
+ np.linspace(起始值, 結束值, 起始與結束的區間內要產生幾個元素 )：只要給定陣列的區間(起始值、結束值)，就可以要求在這個區間內產生幾個元素。
+ arange(a,b,c)
   + 不包含 b 由 a 開始 以固定間隔 c 來取值
+ linspace(a,b,c,)
   + 包含 b 由 a 開始 切割成 c 個資料
+ linspace(a,b,c,endpoint=False)
   + 不包含 b 由 a 開始 切割成 c 個資料

In [31]:
import numpy as np
a = np.array([6,7,8,9])
b = np.arange(4)
print(type(b))
print(a)
print(b)
c = a - b
print(c)
d = b ** 2
print(d)


<class 'numpy.ndarray'>
[6 7 8 9]
[0 1 2 3]
[6 6 6 6]
[0 1 4 9]


In [46]:
import numpy as np
f = np.array([5,-1,3,9,0])
dataList = []
for v in f:
    if v <= 3:
        dataList.append(v)
f = np.array(dataList)     
print(f)

[-1  3  0]


In [47]:
import numpy as np
f = np.array([5,-1,3,9,0])
show = np.array([True,True,False,False,True])
f[show]

array([ 5, -1,  0])

In [44]:
import numpy as np
f = np.array([5,-1,3,9,0])
print(f <= 3 )
print(f[f <= 3])
f[f <= 3] = 1
print(f)

[False  True  True False  True]
[-1  3  0]
[5 1 1 9 1]


In [49]:
import numpy as np
x = np.empty((2,4))#空矩陣
print(x)
z = np.zeros((2,4))#零矩陣
print(z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [58]:
import numpy as np
x = np.ones((2,4))
print(x)
x2 = np.full((2,4),6)
print(x2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[6 6 6 6]
 [6 6 6 6]]


### linspace arange

In [65]:
import numpy as np
x = np.linspace(1,10,6)
print(x)
x = np.linspace(1,10,6).reshape((3,2))
print(x)
x = np.arange(8)
print(x)
x = np.arange(8).reshape((2,4))
print(x)
x = np.arange(8).reshape((4,2))
print(x)

[ 1.   2.8  4.6  6.4  8.2 10. ]
[[ 1.   2.8]
 [ 4.6  6.4]
 [ 8.2 10. ]]
[0 1 2 3 4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [66]:
import numpy as np
r1 = np.arange(25,30,0.5)
print(r1)

[25.  25.5 26.  26.5 27.  27.5 28.  28.5 29.  29.5]


## 陣列指定位置取值
+ 間隔選取 [::c]
  + 以 1 維陣列來說明 x[a:b:c]
  + a：選取資料的起始索引
  + b：選取資料的結束索引 +1
  + c：選取資料間隔，以索引值可以被此值整除的元素，不指定表示 1
+ 倒序 [::-1]
  + 只是單純的把順序反過來

In [74]:
import numpy as np
a = np.arange(1,10)
print(a)
print(a[1])
print(a[2:])
print(a[-4:-1])
print(a[::-1])

[1 2 3 4 5 6 7 8 9]
2
[3 4 5 6 7 8 9]
[6 7 8]
[9 8 7 6 5 4 3 2 1]


In [80]:
import numpy as np
a = np.arange(1,10).reshape((3,3))
print(a)
print(a[0])
print(a[1][1])
print(a[2][1])
print(a[2,1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
5
8
8


In [90]:
import numpy as np
a = np.arange(1,10).reshape((3,3))
print(a)
print(a[1,1:3])
print("="*100)
print(a[:,1])
print("="*100)
a[1,2] = 75
print(a)
print("="*100)
a[:,0] = [100,101,102]
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[5 6]
[2 5 8]
[[ 1  2  3]
 [ 4  5 75]
 [ 7  8  9]]
[[100   2   3]
 [101   5  75]
 [102   8   9]]


In [96]:
import numpy as np
a = np.arange(0,36).reshape((6,6))
print(a)
print("===1===")
print(a[0,3:5])
print("===2===")
print(a[4:,4:])
print("===3===")
print(a[:3,:3])
print("===4===")
print(a[:,2])
print("===5===")
print(a[2:5,1:3])

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
===1===
[3 4]
===2===
[[28 29]
 [34 35]]
===3===
[[ 0  1  2]
 [ 6  7  8]
 [12 13 14]]
===4===
[ 2  8 14 20 26 32]
===5===
[[13 14]
 [19 20]
 [25 26]]


## 重設新陣列
+ resize 這個動作會依據原本的陣列再設定指定大小的新陣列。 
+ resize 動作的參數如下：
+ numpy.resize(arr1，shape1)
  + arr1：原本的陣列
  + shape1：新規劃的大小
+ 如果規劃的新陣列比較大，將會重新複製原有陣列的資料，填滿新的儲存格。
+ resize 這個動作***建立新的陣列***，而 reshape 則是依據原有的重新規劃，仍會受到原有陣列影響。
+ transpose()轉置

In [100]:
import numpy as np
a = np.array([[1,2,3],
              [4,5,6]])
print(a)
print(a.shape)
b = a.reshape((1,6))
print(b)
print("======================")
b[0,1] = 99
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2 3 4 5 6]]
[[ 1 99  3]
 [ 4  5  6]]
[[ 1 99  3  4  5  6]]
